apiVersion: apps/v1
kind: Deployment
metadata:
  name: movflixv1
  labels:
    app: movflixv1
spec:
  replicas: 1
  template:
    metadata:
      name: movflixv1
      labels:
        app: movflixv1
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: movflixv1
        image: moflixregistry.azurecr.io/movflix-image:v1
        resources:
          limits:
            cpu: 1
            memory: 800M
        ports:
          - containerPort: 80
  selector:
    matchLabels:
      app: movflixv1
---
apiVersion: v1
kind: Service
metadata:
  name: movflixv1
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: movflixv1